### ISSUE TITLE
run_install with --global throws permission denied

### ISSUE THREAD

**Issue by rhyek** [pnpm/action-setup#10] opened 2021-02-19 02:26 UTC
With config:
```yaml
    - name: Setup pnpm
      uses: pnpm/action-setup@v1.2.1
      with:
        version: 5.17.2
        run_install: |
          - args: [--global, typescript, ts-node]
```

I get the following:
 ```sh
Run pnpm/action-setup@v1.2.1
  with:
    version: 5.17.2
    run_install: - args: [--global, typescript, ts-node]
  
    dest: ~/setup-pnpm
    bin_dest: ~/setup-pnpm/.bin
    registry: https://registry.npmjs.com
  env:
    DOCKER_BUILDKIT: 1
Running self-installer...
  Downloading https://registry.npmjs.org/pnpm/-/pnpm-5.17.2.tgz
Installation Completed!
Running pnpm install --global typescript ts-node...
   ERROR  EACCES: permission denied, mkdir '/usr/local/pnpm-global'
  
  
Error: Command pnpm install --global typescript ts-node (cwd: undefined) exits with status 1
```

**Comment by KSXGitHub** [comment] 2021-02-19 02:36
I must know the cause before I fix this. Can you please try this?

```yaml
    - name: Setup pnpm
      uses: pnpm/action-setup@v1.2.1
      with:
        version: 5.17.2
        run_install: false

  - run: pnpm i -g typescript ts-node
```

---

BTW, why didn't you just add `typescript` and `ts-node` to `devDependencies` in `package.json` and then use `pnpx` to execute `tsc` and `ts-node`?

**Comment by rhyek** [comment] 2021-02-19 02:43
Result from test:
![image](https://user-images.githubusercontent.com/702922/108449770-a9a01b80-7229-11eb-8f03-63624d59bea7.png)

> BTW, why didn't you just add typescript and ts-node to devDependencies in package.json and then use pnpx to execute tsc and ts-node?

That's how I was doing it, actually. But for aesthetics' sake, I wanted to use shebangs and run my scripts directly.

**Comment by KSXGitHub** [comment] 2021-02-19 02:56
This could be fixed by having `pnpm` choosing a different directory for global packages (ergo, pnpm/action-setup can't do anything).

You could do a workaround by running `chown` and `chmod` before `pnpm/action-setup`.

> > BTW, why didn't you just add typescript and ts-node to devDependencies in package.json and then use pnpx to execute tsc and ts-node?
> 
> That's how I was doing it, actually. But for aesthetics' sake, I wanted to use shebangs and run my scripts directly.

I guess this is because `#! /usr/bin/env <command>` interprets `<command>` as a binary name? If that is the case, you should try `#! /usr/bin/env -S <command>`.

**Comment by rhyek** [comment] 2021-02-19 03:14
Beautiful. `#!/usr/bin/env -S pnpx ts-node-transpile-only` works and is way better since I don't have to worry about either risking installing typescript twice or keeping my project's version and pnpm i -g typescript@version synced.

Thanks!

**Comment by KSXGitHub** [comment] 2021-02-19 03:21
Be aware that `-S` is a GNU extension, it does not work on macOS, BSD, or any pure POSIX implementation.

**Comment by rhyek** [comment] 2021-02-19 03:21
> (ergo, pnpm/action-setup can't do anything).
 You could do a workaround by running chown and chmod before pnpm/action-setup.

Maybe that should be mentioned in the readme. In any case, feel free to close the issue.

**Closed** 2021-02-19 03:21 UTC

**Comment by KSXGitHub** [comment] 2021-02-19 03:25
Another thing, instead of relying on `-S` and `pnpx`, you can just add `$(pwd)/node_modules/.bin` to `PATH`, it would enable you to do just this:

```sh
#! /usr/bin/env ts-node-transpile-only
```

**Comment by rhyek** [comment] 2021-02-19 03:30
Excellent point.

**Comment by KSXGitHub** [comment] 2021-02-19 03:37
In case you aren't aware, [this is how you add a path in GitHub Workflow](https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#adding-a-system-path).
